routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PagesController@home');
Route::get('/faq', 'PagesController@faq'); //will call faq function from controller
Route::get('/progress', 'TicketController@progress');

Route::get('/request', 'TicketController@create');


Route::post('request',
    ['as' => 'request_store', 'uses' => 'TicketController@store']);


//---------------------------------------------------------



Route::resource('its','itsController');

Route::get('showuser/{id}',
    ['as' => 'showuser', 'uses' => 'itsController@showuser']);


Route::resource('ticket','itsCRUDController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/faq.blade.php
@extends('master')
@section('title', 'FAQ')
@section('faqpage')
    class="active"
@endsection

@section('content')
    <div class="container">
    <p><h2>Frequently Asked Questions</h2></p>
    <div class="list-group">
        <a href="#" class="list-group-item active">
            <h4 class="list-group-item-heading">How do i visit myDesktop?</h4>
            <p class="list-group-item-text">Log in to myRMIT and there’s is a list of link at the right bottom, there’s is a myDesktop button. </p>
        </a>
    </div>

    <div class="list-group">
        <a href="#" class="list-group-item active">
            <h4 class="list-group-item-heading">How do i print paper in RMIT?</h4>
            <p class="list-group-item-text">
                Follow these steps and it’s done: <br>
                1. Send your document to be printed (use myDesktop if you are printing from your own device)<br>
                2. Go to a Ricoh multi-function device<br>
                3. Register your card. Already registered? Go to step 4.<br>
                4. Swipe your student card on the printer and print.<br>

            </p>
        </a>
    </div>

    <div class="list-group">
        <a href="#" class="list-group-item active">
            <h4 class="list-group-item-heading">
                How do i report an incident?
            </h4>
            <p class="list-group-item-text">If you see something suspicious, it’s your responsibility to report it.
                Whether it’s unusual system activity you’ve noticed, a password breach or a suspected hacking attempt,
                the IT Security team are your first call in providing advice and taking action.
                Prompt reporting ensures that potential threats are isolated and steps can be taken to limit the potential impact to students,
                colleagues and the university.<br><br>
            <h4>For urgent incidents and advice</h4>
            Service and Support Centre: Phone +61 3 992 58888<br>
            <h4>For non-urgent requests and queries</h4>
            Please drop down a email to its.csit.rmit.edu.au
            </p>
        </a>
    </div>
    </div>

@endsection

resources/views/footer.blade.php
<footer class="well-sm navbar navbar-absolute-bottom">
    <div class="row">
        <div class="branded-footer-left col-xs-12">Copyright © 2016 RMIT University |
            <a href="http://www.rmit.edu.au/utilities/disclaimer/" target="_blank">Disclaimer</a> |
            <a href="http://www.rmit.edu.au/utilities/privacy/" target="_blank">Privacy</a> |
            <a href="http://www.rmit.edu.au/utilities/website-feedback/" target="_blank">Website feedback</a> |
            ABN 49 781 030 034 | CRICOS provider number: 00122A
        </div>
    </div>
</footer>

resources/views/its.blade.php
@extends('master')
@section('title', 'ITS')
@section('completepage')
    <li><a href="/assignment1ver2/public/request">REQUEST A SERVICE</a></li>
    <li><a href="#">REPORT AN ISSUE</a></li>
    <li><a href="#">FEEDBACK</a></li>
@endsection
@section('itspage')
    class="active"
@endsection
@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

        <div class="panel panel-default">
                <div class="panel-heading">
                        <h3 class="panel-title">Database</h3>
                    </div>
                <div class="panel-body">

                    <table class="table">
                        <tr>
                            <th> ID </th>
                            <th> Name </th>
                            {{--<th> Email </th>--}}
                            {{--<th> Tel </th>--}}
                            {{--<th> Operating System </th>--}}
                            {{--<th> Type</th>--}}
                            <th> Description </th>
                            <th>Status</th>
                            <th width="280px">Action</th>

                        </tr>
                        @foreach($ticket as $its)
                        {{--<tr>--}}

                            {{--<td> {{$its->id}} </td>--}}
                            {{--<td> {{$its->name}} </td>--}}
                            {{--<td> {{$its->email}} </td>--}}
                            {{--<td> {{$its->phone}} </td>--}}
                            {{--<td> {{$its->opsystype}} </td>--}}
                            {{--<td> {{$its->type}} </td>--}}
                            {{--<td> {{$its->desc}} </td>--}}

                        {{--</tr>--}}
                            <tr>
                                <td>{{$its->id}}</td>
                                <td>{{$its->name}}</td>
                                <td>{{$its->desc}}</td>
                                <td>{{$its->type}}</td>
                                <td>
                                    <a class="btn btn-info" href="{{ route('ticket.show',$its->id) }}"}>Show</a>
                                    {!! Form::open(['method' => 'DELETE','route' => ['ticket.destroy', $its->id],'style'=>'display:inline']) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                    </table>

                 </div>


            </div>





@endsection

resources/views/itshome.blade.php
@extends('master')
@section('title', 'Home')
@section('homepage')
    class="active"
@endsection
@section('content')
    <div class="container">

        <div class="jumbotron">
            <h1>Hello there!</h1>
            <p> Information Technology Services (ITS) provides RMIT University with information and communication
                technology in support of RMIT’s research, learning teaching and administrative activities</p>
            {{--<table>--}}
                {{--<tr>--}}
                    {{--<td><a class="btn btn-primary btn-lg btn-group-justified"  href="#" role="button">Request a Service</a></td>--}}
                    {{--<td><a class="btn btn-primary btn-lg btn-group-justified"  href="#" role="button">Report an Issue</a></td>--}}
                    {{--<td><a class="btn btn-primary btn-lg btn-group-justified" href="#" role="button">Track Progress</a></td>--}}


                {{--</tr>--}}
            {{--</table>--}}
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <div class="caption">
                            <h3>Request a Service <span class="glyphicon glyphicon-shopping-cart btn-lg" aria-hidden="true"></span> </h3>
                            <p>Need something? We are here to help!</p>
                            <p><a href="/assignment1ver2/public/request" class="btn btn-primary" role="button">REQUEST</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <div class="caption">
                            <h3>Report an Issue <span class="glyphicon glyphicon-wrench btn-lg" aria-hidden="true"></span></h3>
                            <p> Let us know if you found any issues </p>
                            <p><a href="#" class="btn btn-primary" role="button">REPORT</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <div class="caption">
                            <h3>Feedback <span class="glyphicon glyphicon-refresh btn-lg" aria-hidden="true"></span></h3>
                            <p>We need your feedback. Tell us how we do!</p>
                            <p><a href="#" class="btn btn-primary" role="button">FEEDBACK</a></p>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    </div>
@endsection

resources/views/master.blade.php
<html>
<head>
        <title> @yield('title') </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
        <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

        <div class="media-left">
                <a href="#">
                        <img
                    class="media-object" src="http://www.simge.edu.sg/pub/groups/webcontentmanager/documents/sim_university_logo/c2lt/mdaw/~edisp/sim000610.png" alt="">
                    </a>
            </div>
@include('shared.navbar')
@yield('content')
@include('footer')
</body>
</html>

resources/views/request.blade.php
@extends('master')
@section('title', "Ticket Submission ")
@section('completepage')
    <li class="active"><a href="/assignment1ver2/public/request">REQUEST A SERVICE</a></li>
    <li><a href="#">REPORT AN ISSUE</a></li>
    <li><a href="#">FEEDBACK</a></li>
    @endsection
@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    {!! Form::model($ticket, ['route' => 'request_store']) !!}

    <div class="container">
                <h2>Request A Service</h2>
                <div class="jumbotron">
                        <div class="form-group">
                                <h3>Name:</h3>
                                {!! Form::text('name', '', ['class' => 'form-control']) !!}
                            <br> </div>

                        <div class="form-group">
                                <h3>E-mail:</h3>
                                  {!! Form::text('email', '', ['class' => 'form-control']) !!}
                                <br></div>

                        <div class="form-group">
                                <h3>Tel:</h3>
                                    {!! Form::text('phone', '', ['class' => 'form-control']) !!}
                                <br> </div>

                        <div class="form-group">
                                <h3>Operating System ( e.g MAC or Windows ):</h3>
                                    {!! Form::text('opsystype', '', ['class' => 'form-control']) !!}
                                <br> </div>

                        {!! Form::hidden('type', 'Pending', ['class' => 'form-control']) !!}
                        {!! Form::hidden('escalation', '0', ['class' => 'form-control']) !!}
                        {!! Form::hidden('priority', 'Not set', ['class' => 'form-control']) !!}
                        {!! Form::hidden('comment', 'No comment yet', ['class' => 'form-control']) !!}


                         <div class="form-group">
                               <h3>Description:</h3>
                            {!! Form::textarea('desc', '', ['class' => 'form-control']) !!}
                                    </div>
                                <br>
                                <button class="btn btn-default" align="right" >Submit</button>



                        </form>
                    </div>
                </div>




    {!! Form::close() !!}
@endsection

resources/views/showuser.blade.php
@extends('master')
@section('completepage')
    <li><a href="/assignment1ver2/public/request">REQUEST A SERVICE</a></li>
    <li><a href="#">REPORT AN ISSUE</a></li>
    <li><a href="#">FEEDBACK</a></li>
@endsection
@section('progresspage')
    class="active"
@endsection
@section('content')
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2> Show Query</h2>
                    </div>
                    <div class="pull-right">
                        <a class="btn btn-primary" href="/assignment1ver2/public/progress"> Back</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Name:</strong>
                        {{ $ticket->name}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Email:</strong>
                        {{ $ticket->email}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Phone:</strong>
                        {{ $ticket->phone}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Operating System:</strong>
                        {{ $ticket->opsystype}}
                    </div>
                </div>



                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        {{ $ticket->desc}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Enquiry Status:</strong>
                        {{ $ticket->type}}
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Comment:</strong>


                        @if ($ticket->comment != 'No comment yet')
                            {{--@foreach($comment as $comments)--}}
                            {{ $ticket->comment}}


                            {{--@endforeach--}}
                            @else
                            <p> *Your query hasn't been resolved*</p>
                        @endif


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/trackprogress.blade.php
@extends('master')
@section('title', 'Tracking Progress')
@section('completepage')
    <li><a href="/assignment1ver2/public/request">REQUEST A SERVICE</a></li>
    <li><a href="#">REPORT AN ISSUE</a></li>
    <li><a href="#">FEEDBACK</a></li>
@endsection
@section('progresspage')
    class="active"
@endsection
@section('content')

        
            <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><h4>Tracking Progress</h4></div>
                    <div class="panel-body">
                        </div>
        <div class="container-fluid">
            {{--<div class="jumbotron">--}}
                    <!-- Table -->
                    <table class="table">
                           <tr>
                                   <th>Ticket Number</th>
                                   <th>Name</th>
                                   <th>Email</th>
                                   <th>Description</th>
                                   <th>Status</th>
                                    <th></th>
                               </tr>

                @foreach($ticket as $its)
                            <tr>
                                    <td>{{$its->id}}</td>
                                    <td>{{$its->name}}</td>
                                    <td>{{$its->email}}</td>
                                    <td>{{$its->desc}}</td>
                                    <td>{{$its->type}}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('showuser',$its->id) }}"}>Show</a>
                                    </td>
                                </tr>
                @endforeach

                        </table>
                </div>
    {{--</div>--}}
            </div>

@endsection