routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PagesController@home');
Route::get('/faq', 'PagesController@faq'); //will call faq function from controller
Route::get('/progress', 'TicketController@progress');

Route::get('/request', 'TicketController@create');


Route::post('request',
    ['as' => 'request_store', 'uses' => 'TicketController@store']);


//---------------------------------------------------------



Route::resource('its','itsController');

Route::get('showuser/{id}',
    ['as' => 'showuser', 'uses' => 'itsController@showuser']);


Route::resource('ticket','itsCRUDController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/CRUD/edit.blade.php
@extends('master')
@section('itspage')
    class="active"
    @endsection
@section('content')

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="container">
        <div class="jumbotron">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Answer Query</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('ticket.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    {!! Form::model($ticket, ['method' => 'PATCH','route' => ['ticket.update', $ticket->id]]) !!}
    @include('CRUD.form')
    {!! Form::close() !!}


{{--    {!! Form::model($comment, ['method' => 'POST','route' => 'its.store']) !!}--}}
    {!! Form::model($comment, ['method' => 'POST','route' => 'its.store']) !!}

      <div class="form-group">
       <strong>Comment:</strong>
{{--          {!! Form::textarea('comment', null, array('placeholder' => 'Comment','class' => 'form-control')) !!}--}}
          {!! Form::textarea('comment', '', ['class' => 'form-control']) !!}
        </div>

            {!! Form::hidden('id',  $ticket->id, ['class' => 'form-control']) !!}
        <button type="submit" class="btn btn-primary">Submit Comment</button>
    {!! Form::close() !!}
        </div>
    </div>


@endsection

resources/views/CRUD/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $ticket->name}}
             {!! Form::hidden('name',  $ticket->name, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $ticket->email}}
            {!! Form::hidden('email',  $ticket->email, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Phone:</strong>
            {{ $ticket->phone}}
            {!! Form::hidden('phone',  $ticket->phone, ['class' => 'form-control']) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Operating System:</strong>
            {{ $ticket->opsystype}}
            {!! Form::hidden('opsystype',  $ticket->opsystype, ['class' => 'form-control']) !!}
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Description:</strong>
            {{ $ticket->desc}}
            {!! Form::hidden('desc',  $ticket->desc, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Enquiry Status:</strong>
            {!! Form::text('type', null, array('placeholder' => 'Enquiry Status','class' => 'form-control')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <button type="submit" class="btn btn-primary">Update Status</button>
    </div>
</div>

resources/views/CRUD/show.blade.php
@extends('master')
@section('itspage')
    class="active"
@endsection
@section('content')
    <div class="container">
     <div class="jumbotron">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Query</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('ticket.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $ticket->name}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $ticket->email}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone:</strong>
                {{ $ticket->phone}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Operating System:</strong>
                {{ $ticket->opsystype}}
            </div>
        </div>



        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $ticket->desc}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Enquiry Status:</strong>
                {{ $ticket->type}}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Comment:</strong>
                @if ($ticket->comment != 'No comment yet')
                    {{--@foreach($comment as $comments)--}}
                    {{ $ticket->comment}}


                    {{--@endforeach--}}
                @else
                    <p> *No comment yet*</p>
                @endif

            </div>
        </div>
        <a class="btn btn-warning" href="{{ route('ticket.edit',$ticket->id) }}">Edit</a>
    </div>
     </div>
    </div>
@endsection